### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432 [0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)

### ISSUE THREAD

**Issue by izgzhen** [KeegJordan/CSE403#27]
```
$ npm run dev

> q-review@0.1.0 dev /Users/zhen/Repos/cse403/Qreview
> concurrently --kill-others "nodemon index.js" "npm run ngrok"

[1] 
[1] > q-review@0.1.0 ngrok /Users/zhen/Repos/cse403/Qreview
[1] > ./ngrok http 5000 & ./scripts/url.sh
[1] 
[0] [nodemon] 1.18.10
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: *.*
[0] [nodemon] starting `node index.js`
[1] Server running at: https://0703988f.ngrok.io
[0] App listening on port 5000
[0] (node:1936) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
[0] (node:1936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:1936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by izgzhen** [comment]
macOS

**Comment by izgzhen** [comment]
Issues still persists.

**Comment by ryanlozon** [comment]
I'm running into the same issue.
